name: ms_bing_pipe_test
description: ''
version: 0.0.1
author: abhinav@simpledatalabs.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: msbingpipetest
  parentArtefactID: abhinavsimpledatalabscomteam
  buildSystem: maven
  author: null
  createdAt: '2024-08-30 09:20:39'
pipelines:
  pipelines/test_pipeline:
    name: test_pipeline
    description: ''
    author: abhinav@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-08-30 09:20:39'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-30 09:20:39'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-08-30T09:20:39.557161Z'
  name: plibMaven
  version: 8.0.31
  id: '761370548'
  createdAt: '2024-08-30T09:20:39.557161Z'
  type: plibMaven
projectDependencies:
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-08-30 09:20:23'
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.5.5
    isDefault: true
    author: null
    createdAt: '2024-08-30 09:20:23'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
