name: git_parent_test_mig
description: ''
version: 0.0.1
author: admin@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: gitparenttestmig
  parentArtefactID: adminprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-03-10 05:04:34'
pipelines:
  pipelines/test_mig:
    name: test_mig
    description: ''
    author: admin@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-03-10 05:07:38'
    datasets:
      inputs:
      - datasets/csv_basics
      - datasets/csv_proj
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/csv_proj:
    name: csv_proj
    description: ''
    author: admin@prophecy.io
    createdAt: '2025-03-10 05:08:57'
    mode: batch
    physicalDatasets:
      dev1:
        fabricId: 1842
        datasetType: File
        description: ''
        author: admin@prophecy.io
        createdAt: '2025-03-10 05:08:57'
  datasets/csv_basics:
    name: csv_basics
    description: ''
    author: admin@prophecy.io
    createdAt: '2025-03-10 05:09:34'
    mode: batch
    physicalDatasets:
      dev1:
        fabricId: 1842
        datasetType: File
        description: ''
        author: admin@prophecy.io
        createdAt: '2025-03-10 05:09:34'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems:
    gems/Filter:
      name: Filter
      category: Transform
      subCategory: ''
      description: null
      author: admin@prophecy.io
      mode: batch
      files:
      - src/main/scala/adminprophecyioteam/gitparenttestmig/gems/filter.scala
      gemType: ComponentGem
      dependencies: []
      createdAt: '2025-03-10 05:05:19'
    gems/csv:
      name: csv
      category: Source/Target
      subCategory: File
      description: null
      author: admin@prophecy.io
      mode: batch
      files:
      - src/main/scala/adminprophecyioteam/gitparenttestmig/gems/csv.scala
      gemType: DatasetGem
      dependencies: []
      createdAt: '2025-03-10 05:05:59'
  dependencies: null
functions:
  author: null
  createdAt: '2025-03-10 05:04:34'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-03-10T05:04:34.719746Z'
  name: plibMaven
  version: 8.8.2
  id: '481470693'
  createdAt: '2025-03-10T05:04:34.719746Z'
  type: plibMaven
projectDependencies:
  '39':
    projectUID: 39
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_39.git&subPath=
    version: 0.2.6.2.dev1
    isDefault: true
    author: null
    createdAt: '2025-03-10 05:03:37'
  '40':
    projectUID: 40
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_40.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-03-10 05:03:37'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
