name: ms_bing_test
description: ''
version: 0.0.1
author: abhinav@simpledatalabs.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: msbingtest
  parentArtefactID: abhinavsimpledatalabscomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-08-30 09:15:58'
pipelines:
  pipelines/test_pipeline:
    name: test_pipeline
    description: ''
    author: abhinav@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-30 09:19:30'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-30 09:15:58'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-08-30T09:15:58.458112Z'
  name: plibMaven
  version: 8.0.31
  id: '2062094529'
  createdAt: '2024-08-30T09:15:58.458112Z'
  type: plibMaven
- modifiedAt: '2024-08-30T09:15:58.458112Z'
  name: plibPypi
  version: 1.9.9
  id: '1241973748'
  createdAt: '2024-08-30T09:15:58.458112Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-30 09:15:09'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.26
    isDefault: true
    author: null
    createdAt: '2024-08-30 09:15:09'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
