name: scala_parallel
description: ''
version: 0.0.1
author: abhinav+demo@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scalaparallel
  parentArtefactID: abhinavdemoprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2024-10-01 11:08:39'
pipelines:
  pipelines/test_pipeline:
    name: test_pipeline
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-10-01 11:09:00'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-10-01 11:11:22'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-10-01 11:11:22'
  datasets/customers:
    name: customers
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-10-01 11:11:33'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-10-01 11:11:33'
  datasets/customer_orders:
    name: customer_orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-10-01 14:27:00'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-10-01 14:27:00'
templates: {}
jobs:
  jobs/test_job:
    name: test_job
    description: ''
    fabricUID: 2122
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0/15 * * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/test_pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-10-03 09:56:20'
    author: abhinav+demo@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-01 11:08:39'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-10-01T11:10:38.333478Z'
  name: plibMaven
  version: 8.2.1
  id: '1157459551'
  createdAt: '2024-10-01T11:10:38.333347Z'
projectDependencies:
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-10-01 11:08:20'
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.5.5
    isDefault: false
    author: null
    createdAt: '2024-10-01 17:40:30'
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
