package graph

import io.prophecy.libs._
import udfs.PipelineInitCode._
import udfs.UDFs._
import udfs.ColumnFunctions._
import config.Context
import org.apache.spark._
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.expressions._
import java.time._

object Reformat_agg_dw_impressions {

  def apply(context: Context, in: DataFrame): DataFrame =
    in.select(
      col("in_f_create_agg_dw_impressions")
        .getField("date_time")
        .as("date_time"),
      col("in_f_create_agg_dw_impressions")
        .getField("auction_id_64")
        .as("auction_id_64"),
      col("in_f_create_agg_dw_impressions")
        .getField("user_id_64")
        .cast(LongType)
        .as("user_id_64"),
      col("in_f_create_agg_dw_impressions").getField("tag_id").as("tag_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("venue_id")
        .cast(IntegerType)
        .as("venue_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("inventory_source_id")
        .cast(IntegerType)
        .as("inventory_source_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("session_frequency")
        .cast(IntegerType)
        .as("session_frequency"),
      col("in_f_create_agg_dw_impressions")
        .getField("site_domain")
        .as("site_domain"),
      col("in_f_create_agg_dw_impressions")
        .getField("width")
        .cast(IntegerType)
        .as("width"),
      col("in_f_create_agg_dw_impressions")
        .getField("height")
        .cast(IntegerType)
        .as("height"),
      col("in_f_create_agg_dw_impressions")
        .getField("geo_country")
        .as("geo_country"),
      col("in_f_create_agg_dw_impressions")
        .getField("geo_region")
        .as("geo_region"),
      col("in_f_create_agg_dw_impressions").getField("gender").as("gender"),
      col("in_f_create_agg_dw_impressions")
        .getField("age")
        .cast(IntegerType)
        .as("age"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_member_id")
        .as("seller_member_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_member_id")
        .as("buyer_member_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("creative_id")
        .cast(IntegerType)
        .as("creative_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_currency")
        .as("seller_currency"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_currency")
        .as("buyer_currency"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_bid")
        .cast(DoubleType)
        .as("buyer_bid"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_spend")
        .cast(DoubleType)
        .as("buyer_spend"),
      col("in_f_create_agg_dw_impressions")
        .getField("ecp")
        .cast(DoubleType)
        .as("ecp"),
      col("in_f_create_agg_dw_impressions")
        .getField("reserve_price")
        .cast(DoubleType)
        .as("reserve_price"),
      col("in_f_create_agg_dw_impressions")
        .getField("advertiser_id")
        .as("advertiser_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("campaign_group_id")
        .as("campaign_group_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("campaign_id")
        .as("campaign_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("creative_freq")
        .cast(IntegerType)
        .as("creative_freq"),
      col("in_f_create_agg_dw_impressions")
        .getField("creative_rec")
        .cast(IntegerType)
        .as("creative_rec"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_learn")
        .cast(IntegerType)
        .as("is_learn"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_remarketing")
        .cast(IntegerType)
        .as("is_remarketing"),
      col("in_f_create_agg_dw_impressions")
        .getField("advertiser_frequency")
        .cast(IntegerType)
        .as("advertiser_frequency"),
      col("in_f_create_agg_dw_impressions")
        .getField("advertiser_recency")
        .cast(IntegerType)
        .as("advertiser_recency"),
      col("in_f_create_agg_dw_impressions")
        .getField("user_group_id")
        .cast(IntegerType)
        .as("user_group_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("camp_dp_id")
        .cast(IntegerType)
        .as("camp_dp_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("media_buy_id")
        .cast(IntegerType)
        .as("media_buy_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("media_buy_cost")
        .cast(DoubleType)
        .as("media_buy_cost"),
      col("in_f_create_agg_dw_impressions")
        .getField("brand_id")
        .cast(IntegerType)
        .as("brand_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("cleared_direct")
        .cast(IntegerType)
        .as("cleared_direct"),
      col("in_f_create_agg_dw_impressions")
        .getField("clear_fees")
        .cast(DoubleType)
        .as("clear_fees"),
      col("in_f_create_agg_dw_impressions")
        .getField("media_buy_rev_share_pct")
        .cast(DoubleType)
        .as("media_buy_rev_share_pct"),
      col("in_f_create_agg_dw_impressions")
        .getField("revenue_value")
        .cast(DoubleType)
        .as("revenue_value"),
      col("in_f_create_agg_dw_impressions")
        .getField("pricing_type")
        .as("pricing_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("can_convert")
        .cast(IntegerType)
        .as("can_convert"),
      col("in_f_create_agg_dw_impressions")
        .getField("pub_rule_id")
        .cast(IntegerType)
        .as("pub_rule_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_control")
        .cast(IntegerType)
        .as("is_control"),
      col("in_f_create_agg_dw_impressions")
        .getField("control_pct")
        .cast(DoubleType)
        .as("control_pct"),
      col("in_f_create_agg_dw_impressions")
        .getField("control_creative_id")
        .cast(IntegerType)
        .as("control_creative_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("predicted_cpm")
        .cast(DoubleType)
        .as("predicted_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("actual_bid")
        .cast(DoubleType)
        .as("actual_bid"),
      col("in_f_create_agg_dw_impressions").getField("site_id").as("site_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("content_category_id")
        .cast(IntegerType)
        .as("content_category_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("auction_service_fees")
        .cast(DoubleType)
        .as("auction_service_fees"),
      col("in_f_create_agg_dw_impressions")
        .getField("discrepancy_allowance")
        .cast(DoubleType)
        .as("discrepancy_allowance"),
      col("in_f_create_agg_dw_impressions")
        .getField("forex_allowance")
        .cast(DoubleType)
        .as("forex_allowance"),
      col("in_f_create_agg_dw_impressions")
        .getField("creative_overage_fees")
        .cast(DoubleType)
        .as("creative_overage_fees"),
      col("in_f_create_agg_dw_impressions")
        .getField("fold_position")
        .cast(IntegerType)
        .as("fold_position"),
      col("in_f_create_agg_dw_impressions")
        .getField("external_inv_id")
        .cast(IntegerType)
        .as("external_inv_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("cadence_modifier")
        .cast(DoubleType)
        .as("cadence_modifier"),
      col("in_f_create_agg_dw_impressions").getField("imp_type").as("imp_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("advertiser_currency")
        .as("advertiser_currency"),
      col("in_f_create_agg_dw_impressions")
        .getField("advertiser_exchange_rate")
        .cast(DoubleType)
        .as("advertiser_exchange_rate"),
      col("in_f_create_agg_dw_impressions")
        .getField("ip_address")
        .as("ip_address"),
      col("in_f_create_agg_dw_impressions")
        .getField("publisher_id")
        .as("publisher_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("auction_service_deduction")
        .cast(DoubleType)
        .as("auction_service_deduction"),
      col("in_f_create_agg_dw_impressions")
        .getField("insertion_order_id")
        .as("insertion_order_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("predict_type_rev")
        .cast(IntegerType)
        .as("predict_type_rev"),
      col("in_f_create_agg_dw_impressions")
        .getField("predict_type_goal")
        .cast(IntegerType)
        .as("predict_type_goal"),
      col("in_f_create_agg_dw_impressions")
        .getField("predict_type_cost")
        .cast(IntegerType)
        .as("predict_type_cost"),
      col("in_f_create_agg_dw_impressions")
        .getField("booked_revenue_dollars")
        .cast(DoubleType)
        .as("booked_revenue_dollars"),
      col("in_f_create_agg_dw_impressions")
        .getField("booked_revenue_adv_curr")
        .cast(DoubleType)
        .as("booked_revenue_adv_curr"),
      col("in_f_create_agg_dw_impressions")
        .getField("commission_cpm")
        .cast(DoubleType)
        .as("commission_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("commission_revshare")
        .cast(DoubleType)
        .as("commission_revshare"),
      col("in_f_create_agg_dw_impressions")
        .getField("serving_fees_cpm")
        .cast(DoubleType)
        .as("serving_fees_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("serving_fees_revshare")
        .cast(DoubleType)
        .as("serving_fees_revshare"),
      col("in_f_create_agg_dw_impressions")
        .getField("user_tz_offset")
        .cast(IntegerType)
        .as("user_tz_offset"),
      col("in_f_create_agg_dw_impressions")
        .getField("media_type")
        .cast(IntegerType)
        .as("media_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("operating_system")
        .cast(IntegerType)
        .as("operating_system"),
      col("in_f_create_agg_dw_impressions")
        .getField("browser")
        .cast(IntegerType)
        .as("browser"),
      col("in_f_create_agg_dw_impressions")
        .getField("language")
        .cast(IntegerType)
        .as("language"),
      col("in_f_create_agg_dw_impressions")
        .getField("publisher_currency")
        .as("publisher_currency"),
      col("in_f_create_agg_dw_impressions")
        .getField("publisher_exchange_rate")
        .cast(DoubleType)
        .as("publisher_exchange_rate"),
      col("in_f_create_agg_dw_impressions")
        .getField("media_cost_dollars_cpm")
        .cast(DoubleType)
        .as("media_cost_dollars_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("payment_type")
        .cast(IntegerType)
        .as("payment_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("revenue_type")
        .cast(IntegerType)
        .as("revenue_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_revenue_cpm")
        .cast(DoubleType)
        .as("seller_revenue_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("bidder_id")
        .cast(IntegerType)
        .as("bidder_id"),
      col("in_f_create_agg_dw_impressions").getField("inv_code").as("inv_code"),
      col("in_f_create_agg_dw_impressions")
        .getField("application_id")
        .as("application_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("shadow_price")
        .cast(DoubleType)
        .as("shadow_price"),
      col("in_f_create_agg_dw_impressions")
        .getField("eap")
        .cast(DoubleType)
        .as("eap"),
      col("in_f_create_agg_dw_impressions")
        .getField("datacenter_id")
        .cast(IntegerType)
        .as("datacenter_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("imp_blacklist_or_fraud")
        .cast(IntegerType)
        .as("imp_blacklist_or_fraud"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_expose_domains")
        .cast(IntegerType)
        .as("vp_expose_domains"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_expose_categories")
        .cast(IntegerType)
        .as("vp_expose_categories"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_expose_pubs")
        .cast(IntegerType)
        .as("vp_expose_pubs"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_expose_tag")
        .cast(IntegerType)
        .as("vp_expose_tag"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_expose_age")
        .cast(IntegerType)
        .as("vp_expose_age"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_expose_gender")
        .cast(IntegerType)
        .as("vp_expose_gender"),
      col("in_f_create_agg_dw_impressions")
        .getField("inventory_url_id")
        .cast(IntegerType)
        .as("inventory_url_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("audit_type")
        .cast(IntegerType)
        .as("audit_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_exclusive")
        .cast(IntegerType)
        .as("is_exclusive"),
      col("in_f_create_agg_dw_impressions")
        .getField("truncate_ip")
        .cast(IntegerType)
        .as("truncate_ip"),
      col("in_f_create_agg_dw_impressions")
        .getField("device_id")
        .cast(IntegerType)
        .as("device_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("carrier_id")
        .cast(IntegerType)
        .as("carrier_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("creative_audit_status")
        .cast(IntegerType)
        .as("creative_audit_status"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_creative_hosted")
        .cast(IntegerType)
        .as("is_creative_hosted"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_deduction")
        .cast(DoubleType)
        .as("seller_deduction"),
      col("in_f_create_agg_dw_impressions")
        .getField("city")
        .cast(IntegerType)
        .as("city"),
      col("in_f_create_agg_dw_impressions").getField("latitude").as("latitude"),
      col("in_f_create_agg_dw_impressions")
        .getField("longitude")
        .as("longitude"),
      col("in_f_create_agg_dw_impressions")
        .getField("device_unique_id")
        .as("device_unique_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("package_id")
        .cast(IntegerType)
        .as("package_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("targeted_segments")
        .as("targeted_segments"),
      col("in_f_create_agg_dw_impressions")
        .getField("supply_type")
        .cast(IntegerType)
        .as("supply_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_toolbar")
        .cast(IntegerType)
        .as("is_toolbar"),
      col("in_f_create_agg_dw_impressions")
        .getField("deal_id")
        .cast(IntegerType)
        .as("deal_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("vp_bitmap")
        .cast(LongType)
        .as("vp_bitmap"),
      col("in_f_create_agg_dw_impressions")
        .getField("view_detection_enabled")
        .cast(IntegerType)
        .as("view_detection_enabled"),
      col("in_f_create_agg_dw_impressions")
        .getField("view_result")
        .cast(IntegerType)
        .as("view_result"),
      col("in_f_create_agg_dw_impressions")
        .getField("ozone_id")
        .cast(IntegerType)
        .as("ozone_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_performance")
        .cast(IntegerType)
        .as("is_performance"),
      col("in_f_create_agg_dw_impressions")
        .getField("sdk_version")
        .as("sdk_version"),
      col("in_f_create_agg_dw_impressions")
        .getField("inventory_session_frequency")
        .cast(IntegerType)
        .as("inventory_session_frequency"),
      col("in_f_create_agg_dw_impressions")
        .getField("device_type")
        .cast(IntegerType)
        .as("device_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("dma")
        .cast(IntegerType)
        .as("dma"),
      col("in_f_create_agg_dw_impressions").getField("postal").as("postal"),
      col("in_f_create_agg_dw_impressions")
        .getField("viewdef_definition_id")
        .cast(IntegerType)
        .as("viewdef_definition_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("viewdef_viewable")
        .cast(IntegerType)
        .as("viewdef_viewable"),
      col("in_f_create_agg_dw_impressions")
        .getField("view_measurable")
        .cast(IntegerType)
        .as("view_measurable"),
      col("in_f_create_agg_dw_impressions")
        .getField("viewable")
        .cast(IntegerType)
        .as("viewable"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_secure")
        .cast(IntegerType)
        .as("is_secure"),
      col("in_f_create_agg_dw_impressions")
        .getField("view_non_measurable_reason")
        .cast(IntegerType)
        .as("view_non_measurable_reason"),
      col("in_f_create_agg_dw_impressions")
        .getField("data_costs")
        .as("data_costs"),
      col("in_f_create_agg_dw_impressions")
        .getField("bidder_instance_id")
        .cast(IntegerType)
        .as("bidder_instance_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("campaign_group_freq")
        .cast(IntegerType)
        .as("campaign_group_freq"),
      col("in_f_create_agg_dw_impressions")
        .getField("campaign_group_rec")
        .cast(IntegerType)
        .as("campaign_group_rec"),
      col("in_f_create_agg_dw_impressions")
        .getField("insertion_order_freq")
        .cast(IntegerType)
        .as("insertion_order_freq"),
      col("in_f_create_agg_dw_impressions")
        .getField("insertion_order_rec")
        .cast(IntegerType)
        .as("insertion_order_rec"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_gender")
        .as("buyer_gender"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_age")
        .cast(IntegerType)
        .as("buyer_age"),
      col("in_f_create_agg_dw_impressions")
        .getField("targeted_segment_list")
        .as("targeted_segment_list"),
      col("in_f_create_agg_dw_impressions")
        .getField("custom_model_id")
        .cast(IntegerType)
        .as("custom_model_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("custom_model_last_modified")
        .cast(LongType)
        .as("custom_model_last_modified"),
      col("in_f_create_agg_dw_impressions")
        .getField("custom_model_output_code")
        .as("custom_model_output_code"),
      col("in_f_create_agg_dw_impressions")
        .getField("external_uid")
        .as("external_uid"),
      col("in_f_create_agg_dw_impressions")
        .getField("request_uuid")
        .as("request_uuid"),
      col("in_f_create_agg_dw_impressions")
        .getField("mobile_app_instance_id")
        .cast(IntegerType)
        .as("mobile_app_instance_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("traffic_source_code")
        .as("traffic_source_code"),
      col("in_f_create_agg_dw_impressions")
        .getField("external_request_id")
        .as("external_request_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("stitch_group_id")
        .as("stitch_group_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("deal_type")
        .cast(IntegerType)
        .as("deal_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("ym_floor_id")
        .cast(IntegerType)
        .as("ym_floor_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("ym_bias_id")
        .cast(IntegerType)
        .as("ym_bias_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("bid_priority")
        .cast(IntegerType)
        .as("bid_priority"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_charges")
        .as("buyer_charges"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_charges")
        .as("seller_charges"),
      col("in_f_create_agg_dw_impressions")
        .getField("explore_disposition")
        .cast(IntegerType)
        .as("explore_disposition"),
      col("in_f_create_agg_dw_impressions")
        .getField("device_make_id")
        .cast(IntegerType)
        .as("device_make_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("operating_system_family_id")
        .cast(IntegerType)
        .as("operating_system_family_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("tag_sizes")
        .as("tag_sizes"),
      col("in_f_create_agg_dw_impressions")
        .getField("campaign_group_models")
        .as("campaign_group_models"),
      col("in_f_create_agg_dw_impressions")
        .getField("pricing_media_type")
        .cast(IntegerType)
        .as("pricing_media_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_trx_event_id")
        .cast(IntegerType)
        .as("buyer_trx_event_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_trx_event_id")
        .cast(IntegerType)
        .as("seller_trx_event_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("revenue_auction_event_type")
        .cast(IntegerType)
        .as("revenue_auction_event_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_prebid")
        .cast(BooleanType)
        .as("is_prebid"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_unit_of_trx")
        .cast(BooleanType)
        .as("is_unit_of_trx"),
      col("in_f_create_agg_dw_impressions")
        .getField("imps_for_budget_caps_pacing")
        .cast(IntegerType)
        .as("imps_for_budget_caps_pacing"),
      col("in_f_create_agg_dw_impressions")
        .getField("auction_timestamp")
        .cast(LongType)
        .as("auction_timestamp"),
      col("in_f_create_agg_dw_impressions")
        .getField("two_phase_reduction_applied")
        .cast(BooleanType)
        .as("two_phase_reduction_applied"),
      col("in_f_create_agg_dw_impressions")
        .getField("region_id")
        .cast(IntegerType)
        .as("region_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("media_company_id")
        .cast(IntegerType)
        .as("media_company_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("trade_agreement_id")
        .cast(IntegerType)
        .as("trade_agreement_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("personal_data")
        .as("personal_data"),
      col("in_f_create_agg_dw_impressions")
        .getField("anonymized_user_info")
        .as("anonymized_user_info"),
      col("in_f_create_agg_dw_impressions")
        .getField("gdpr_consent_cookie")
        .as("gdpr_consent_cookie"),
      col("in_f_create_agg_dw_impressions")
        .getField("additional_clearing_events")
        .as("additional_clearing_events"),
      col("in_f_create_agg_dw_impressions")
        .getField("fx_rate_snapshot_id")
        .cast(IntegerType)
        .as("fx_rate_snapshot_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("crossdevice_group_anon")
        .as("crossdevice_group_anon"),
      col("in_f_create_agg_dw_impressions")
        .getField("crossdevice_graph_cost")
        .as("crossdevice_graph_cost"),
      col("in_f_create_agg_dw_impressions")
        .getField("revenue_event_type_id")
        .cast(IntegerType)
        .as("revenue_event_type_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_trx_event_type_id")
        .cast(IntegerType)
        .as("buyer_trx_event_type_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_trx_event_type_id")
        .cast(IntegerType)
        .as("seller_trx_event_type_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("external_creative_id")
        .as("external_creative_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("targeted_segment_details")
        .as("targeted_segment_details"),
      col("in_f_create_agg_dw_impressions")
        .getField("bidder_seat_id")
        .cast(IntegerType)
        .as("bidder_seat_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_whiteops_scanned")
        .cast(BooleanType)
        .as("is_whiteops_scanned"),
      col("in_f_create_agg_dw_impressions")
        .getField("default_referrer_url")
        .as("default_referrer_url"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_curated")
        .cast(BooleanType)
        .as("is_curated"),
      col("in_f_create_agg_dw_impressions")
        .getField("curator_member_id")
        .cast(IntegerType)
        .as("curator_member_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("total_partner_fees_microcents")
        .cast(LongType)
        .as("total_partner_fees_microcents"),
      col("in_f_create_agg_dw_impressions")
        .getField("net_buyer_spend")
        .cast(DoubleType)
        .as("net_buyer_spend"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_prebid_server")
        .cast(BooleanType)
        .as("is_prebid_server"),
      col("in_f_create_agg_dw_impressions")
        .getField("cold_start_price_type")
        .cast(IntegerType)
        .as("cold_start_price_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("discovery_state")
        .cast(IntegerType)
        .as("discovery_state"),
      col("in_f_create_agg_dw_impressions")
        .getField("billing_period_id")
        .cast(IntegerType)
        .as("billing_period_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("flight_id")
        .cast(IntegerType)
        .as("flight_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("split_id")
        .cast(IntegerType)
        .as("split_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("net_media_cost_dollars_cpm")
        .cast(DoubleType)
        .as("net_media_cost_dollars_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("total_data_costs_microcents")
        .cast(LongType)
        .as("total_data_costs_microcents"),
      col("in_f_create_agg_dw_impressions")
        .getField("total_profit_microcents")
        .cast(LongType)
        .as("total_profit_microcents"),
      col("in_f_create_agg_dw_impressions")
        .getField("targeted_crossdevice_graph_id")
        .cast(IntegerType)
        .as("targeted_crossdevice_graph_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("discovery_prediction")
        .cast(DoubleType)
        .as("discovery_prediction"),
      col("in_f_create_agg_dw_impressions")
        .getField("campaign_group_type_id")
        .cast(IntegerType)
        .as("campaign_group_type_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("hb_source")
        .cast(IntegerType)
        .as("hb_source"),
      col("in_f_create_agg_dw_impressions")
        .getField("external_campaign_id")
        .as("external_campaign_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("excluded_targeted_segment_details")
        .as("excluded_targeted_segment_details"),
      col("in_f_create_agg_dw_impressions").getField("trust_id").as("trust_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("predicted_kpi_event_rate")
        .cast(DoubleType)
        .as("predicted_kpi_event_rate"),
      col("in_f_create_agg_dw_impressions")
        .getField("has_crossdevice_reach_extension")
        .cast(BooleanType)
        .as("has_crossdevice_reach_extension"),
      col("in_f_create_agg_dw_impressions")
        .getField("crossdevice_graph_membership")
        .as("crossdevice_graph_membership"),
      col("in_f_create_agg_dw_impressions")
        .getField("total_segment_data_costs_microcents")
        .cast(LongType)
        .as("total_segment_data_costs_microcents"),
      col("in_f_create_agg_dw_impressions")
        .getField("total_feature_costs_microcents")
        .cast(LongType)
        .as("total_feature_costs_microcents"),
      col("in_f_create_agg_dw_impressions")
        .getField("counterparty_ruleset_type")
        .cast(IntegerType)
        .as("counterparty_ruleset_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("log_product_ads")
        .as("log_product_ads"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_line_item_currency")
        .as("buyer_line_item_currency"),
      col("in_f_create_agg_dw_impressions")
        .getField("deal_line_item_currency")
        .as("deal_line_item_currency"),
      col("in_f_create_agg_dw_impressions")
        .getField("measurement_fee_usd")
        .cast(DoubleType)
        .as("measurement_fee_usd"),
      col("in_f_create_agg_dw_impressions")
        .getField("measurement_provider_member_id")
        .cast(IntegerType)
        .as("measurement_provider_member_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("offline_attribution_provider_member_id")
        .cast(IntegerType)
        .as("offline_attribution_provider_member_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("offline_attribution_cost_usd_cpm")
        .cast(DoubleType)
        .as("offline_attribution_cost_usd_cpm"),
      col("in_f_create_agg_dw_impressions")
        .getField("pred_info")
        .cast(IntegerType)
        .as("pred_info"),
      col("in_f_create_agg_dw_impressions")
        .getField("imp_rejecter_do_auction")
        .cast(BooleanType)
        .as("imp_rejecter_do_auction"),
      col("in_f_create_agg_dw_impressions")
        .getField("personal_identifiers")
        .as("personal_identifiers"),
      col("in_f_create_agg_dw_impressions")
        .getField("imp_rejecter_applied")
        .cast(BooleanType)
        .as("imp_rejecter_applied"),
      col("in_f_create_agg_dw_impressions")
        .getField("ip_derived_latitude")
        .cast(FloatType)
        .as("ip_derived_latitude"),
      col("in_f_create_agg_dw_impressions")
        .getField("ip_derived_longitude")
        .cast(FloatType)
        .as("ip_derived_longitude"),
      col("in_f_create_agg_dw_impressions")
        .getField("personal_identifiers_experimental")
        .as("personal_identifiers_experimental"),
      col("in_f_create_agg_dw_impressions")
        .getField("postal_code_ext_id")
        .cast(IntegerType)
        .as("postal_code_ext_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("ecpm_conversion_rate")
        .cast(DoubleType)
        .as("ecpm_conversion_rate"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_residential_ip")
        .cast(BooleanType)
        .as("is_residential_ip"),
      col("in_f_create_agg_dw_impressions")
        .getField("hashed_ip")
        .as("hashed_ip"),
      col("in_f_create_agg_dw_impressions")
        .getField("targeted_segment_details_by_id_type")
        .as("targeted_segment_details_by_id_type"),
      col("in_f_create_agg_dw_impressions")
        .getField("offline_attribution")
        .as("offline_attribution"),
      col("in_f_create_agg_dw_impressions")
        .getField("frequency_cap_type_internal")
        .cast(IntegerType)
        .as("frequency_cap_type_internal"),
      col("in_f_create_agg_dw_impressions")
        .getField("modeled_cap_did_override_line_item_daily_cap")
        .cast(BooleanType)
        .as("modeled_cap_did_override_line_item_daily_cap"),
      col("in_f_create_agg_dw_impressions")
        .getField("modeled_cap_user_sample_rate")
        .cast(DoubleType)
        .as("modeled_cap_user_sample_rate"),
      col("in_f_create_agg_dw_impressions")
        .getField("estimated_audience_imps")
        .cast(FloatType)
        .as("estimated_audience_imps"),
      col("in_f_create_agg_dw_impressions")
        .getField("audience_imps")
        .cast(FloatType)
        .as("audience_imps"),
      col("in_f_create_agg_dw_impressions")
        .getField("district_postal_code_lists")
        .as("district_postal_code_lists"),
      col("in_f_create_agg_dw_impressions")
        .getField("bidding_host_id")
        .cast(IntegerType)
        .as("bidding_host_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("buyer_dpvp_bitmap")
        .cast(LongType)
        .as("buyer_dpvp_bitmap"),
      col("in_f_create_agg_dw_impressions")
        .getField("seller_dpvp_bitmap")
        .cast(LongType)
        .as("seller_dpvp_bitmap"),
      col("in_f_create_agg_dw_impressions")
        .getField("browser_code_id")
        .cast(IntegerType)
        .as("browser_code_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_prebid_server_included")
        .cast(IntegerType)
        .as("is_prebid_server_included"),
      col("in_f_create_agg_dw_impressions")
        .getField("feature_tests_bitmap")
        .cast(IntegerType)
        .as("feature_tests_bitmap"),
      col("in_f_create_agg_dw_impressions")
        .getField("private_auction_eligible")
        .cast(BooleanType)
        .as("private_auction_eligible"),
      col("in_f_create_agg_dw_impressions")
        .getField("chrome_traffic_label")
        .cast(IntegerType)
        .as("chrome_traffic_label"),
      col("in_f_create_agg_dw_impressions")
        .getField("is_private_auction")
        .cast(BooleanType)
        .as("is_private_auction"),
      col("in_f_create_agg_dw_impressions")
        .getField("creative_media_subtype_id")
        .cast(IntegerType)
        .as("creative_media_subtype_id"),
      col("in_f_create_agg_dw_impressions")
        .getField("allowed_media_types")
        .as("allowed_media_types")
    )

}
