package io.prophecy.pipelines.first_agg_platform_video_analytics.graph.Main_Graph.Validate_Pick_Video_Events

import io.prophecy.libs._
import io.prophecy.pipelines.first_agg_platform_video_analytics.udfs.PipelineInitCode._
import io.prophecy.pipelines.first_agg_platform_video_analytics.udfs.UDFs._
import io.prophecy.pipelines.first_agg_platform_video_analytics.udfs.ColumnFunctions._
import io.prophecy.pipelines.first_agg_platform_video_analytics.graph.Main_Graph.Validate_Pick_Video_Events.config.Context
import org.apache.spark._
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.expressions._
import java.time._

object Reformat_flatten {

  def apply(context: Context, in: DataFrame): DataFrame =
    in.select(
      col("unflattened_struct_out.date_time").as("date_time"),
      col("unflattened_struct_out.auction_id_64").as("auction_id_64"),
      col("unflattened_struct_out.buyer_member_id").as("buyer_member_id"),
      col("unflattened_struct_out.seller_member_id").as("seller_member_id"),
      col("unflattened_struct_out.advertiser_id").as("advertiser_id"),
      col("unflattened_struct_out.publisher_id").as("publisher_id"),
      col("unflattened_struct_out.site_id").as("site_id"),
      col("unflattened_struct_out.tag_id").as("tag_id"),
      col("unflattened_struct_out.insertion_order_id").as("insertion_order_id"),
      col("unflattened_struct_out.campaign_group_id").as("campaign_group_id"),
      col("unflattened_struct_out.campaign_id").as("campaign_id"),
      col("unflattened_struct_out.creative_id").as("creative_id"),
      col("unflattened_struct_out.creative_freq").as("creative_freq"),
      col("unflattened_struct_out.creative_rec").as("creative_rec"),
      col("unflattened_struct_out.brand_id").as("brand_id"),
      col("unflattened_struct_out.geo_country").as("geo_country"),
      col("unflattened_struct_out.width").as("width"),
      col("unflattened_struct_out.height").as("height"),
      col("unflattened_struct_out.deal_id").as("deal_id"),
      col("unflattened_struct_out.video_was_served").as("video_was_served"),
      col("unflattened_struct_out.video_started").as("video_started"),
      col("unflattened_struct_out.video_was_skipped").as("video_was_skipped"),
      col("unflattened_struct_out.video_had_error").as("video_had_error"),
      col("unflattened_struct_out.video_hit_25_pct").as("video_hit_25_pct"),
      col("unflattened_struct_out.video_hit_50_pct").as("video_hit_50_pct"),
      col("unflattened_struct_out.video_hit_75_pct").as("video_hit_75_pct"),
      col("unflattened_struct_out.video_completed").as("video_completed"),
      col("unflattened_struct_out.imp_type").as("imp_type"),
      col("unflattened_struct_out.advertiser_currency")
        .as("advertiser_currency"),
      col("unflattened_struct_out.publisher_currency").as("publisher_currency"),
      col("unflattened_struct_out.site_domain").as("site_domain"),
      col("unflattened_struct_out.application_id").as("application_id"),
      col("unflattened_struct_out.media_cost_dollars_cpm")
        .as("media_cost_dollars_cpm"),
      col("unflattened_struct_out.booked_revenue_dollars")
        .as("booked_revenue_dollars"),
      col("unflattened_struct_out.seller_revenue_cpm").as("seller_revenue_cpm"),
      col("unflattened_struct_out.vp_bitmap").as("vp_bitmap"),
      col("unflattened_struct_out.buyer_currency").as("buyer_currency"),
      col("unflattened_struct_out.is_learn").as("is_learn"),
      col("unflattened_struct_out.external_inv_id").as("external_inv_id"),
      col("unflattened_struct_out.pub_rule_id").as("pub_rule_id"),
      col("unflattened_struct_out.predict_type_rev").as("predict_type_rev"),
      col("unflattened_struct_out.predict_type_goal").as("predict_type_goal"),
      col("unflattened_struct_out.media_type").as("media_type"),
      col("unflattened_struct_out.venue_id").as("venue_id"),
      col("unflattened_struct_out.payment_type").as("payment_type"),
      col("unflattened_struct_out.revenue_type").as("revenue_type"),
      col("unflattened_struct_out.viewdef_definition_id")
        .as("viewdef_definition_id"),
      col("unflattened_struct_out.advertiser_exchange_rate")
        .as("advertiser_exchange_rate"),
      col("unflattened_struct_out.publisher_exchange_rate")
        .as("publisher_exchange_rate"),
      col("unflattened_struct_out.vp_expose_pubs").as("vp_expose_pubs"),
      col("unflattened_struct_out.vp_expose_tag").as("vp_expose_tag"),
      col("unflattened_struct_out.vp_expose_categories")
        .as("vp_expose_categories"),
      col("unflattened_struct_out.playback_method").as("playback_method"),
      col("unflattened_struct_out.video_context").as("video_context"),
      col("unflattened_struct_out.player_size_id").as("player_size_id"),
      col("unflattened_struct_out.supply_type").as("supply_type"),
      col("unflattened_struct_out.vp_expose_domains").as("vp_expose_domains"),
      col("unflattened_struct_out.view_result").as("view_result"),
      col("unflattened_struct_out.view_non_measurable_reason")
        .as("view_non_measurable_reason"),
      col("unflattened_struct_out.error_code").as("error_code"),
      col("unflattened_struct_out.request_imp_type").as("request_imp_type"),
      col("unflattened_struct_out.call_type").as("call_type"),
      col("unflattened_struct_out.companion_creative_id")
        .as("companion_creative_id"),
      col("unflattened_struct_out.companion_imps").as("companion_imps"),
      col("unflattened_struct_out.companion_clicks").as("companion_clicks"),
      col("unflattened_struct_out.user_id_64").as("user_id_64"),
      col("unflattened_struct_out.geo_region").as("geo_region"),
      col("unflattened_struct_out.gender").as("gender"),
      col("unflattened_struct_out.age").as("age"),
      col("unflattened_struct_out.operating_system").as("operating_system"),
      col("unflattened_struct_out.browser").as("browser"),
      col("unflattened_struct_out.language").as("language"),
      col("unflattened_struct_out.latitude").as("latitude"),
      col("unflattened_struct_out.longitude").as("longitude"),
      col("unflattened_struct_out.device_id").as("device_id"),
      col("unflattened_struct_out.carrier_id").as("carrier_id"),
      col("unflattened_struct_out.device_type").as("device_type"),
      col("unflattened_struct_out.dma").as("dma"),
      col("unflattened_struct_out.postal").as("postal"),
      col("unflattened_struct_out.city").as("city"),
      col("unflattened_struct_out.request_uuid").as("request_uuid"),
      col("unflattened_struct_out.tag_sizes").as("tag_sizes"),
      col("unflattened_struct_out.user_tz_offset").as("user_tz_offset"),
      col("unflattened_struct_out.fold_position").as("fold_position"),
      col("unflattened_struct_out.anonymized_user_info")
        .as("anonymized_user_info"),
      col("unflattened_struct_out.personal_data").as("personal_data"),
      col("unflattened_struct_out.inventory_url_id").as("inventory_url_id"),
      col("unflattened_struct_out.predicted_100pd_video_completion_rate")
        .as("predicted_100pd_video_completion_rate"),
      col("unflattened_struct_out.inventory_source_id")
        .as("inventory_source_id"),
      col("unflattened_struct_out.session_frequency").as("session_frequency"),
      col("unflattened_struct_out.is_control").as("is_control"),
      col("unflattened_struct_out.device_unique_id").as("device_unique_id"),
      col("unflattened_struct_out.targeted_segments").as("targeted_segments"),
      col("unflattened_struct_out.seller_currency").as("seller_currency"),
      col("unflattened_struct_out.is_toolbar").as("is_toolbar"),
      col("unflattened_struct_out.control_pct").as("control_pct"),
      col("unflattened_struct_out.advertiser_frequency")
        .as("advertiser_frequency"),
      col("unflattened_struct_out.advertiser_recency").as("advertiser_recency"),
      col("unflattened_struct_out.ozone_id").as("ozone_id"),
      col("unflattened_struct_out.is_performance").as("is_performance"),
      col("unflattened_struct_out.sdk_version").as("sdk_version"),
      col("unflattened_struct_out.media_buy_id").as("media_buy_id"),
      col("unflattened_struct_out.camp_dp_id").as("camp_dp_id"),
      col("unflattened_struct_out.user_group_id").as("user_group_id"),
      col("unflattened_struct_out.package_id").as("package_id"),
      col("unflattened_struct_out.campaign_group_freq")
        .as("campaign_group_freq"),
      col("unflattened_struct_out.campaign_group_rec").as("campaign_group_rec"),
      col("unflattened_struct_out.insertion_order_freq")
        .as("insertion_order_freq"),
      col("unflattened_struct_out.insertion_order_rec")
        .as("insertion_order_rec"),
      col("unflattened_struct_out.buyer_gender").as("buyer_gender"),
      col("unflattened_struct_out.buyer_age").as("buyer_age"),
      col("unflattened_struct_out.targeted_segment_list")
        .as("targeted_segment_list"),
      col("unflattened_struct_out.custom_model_id").as("custom_model_id"),
      col("unflattened_struct_out.custom_model_last_modified")
        .as("custom_model_last_modified"),
      col("unflattened_struct_out.custom_model_output_code")
        .as("custom_model_output_code"),
      col("unflattened_struct_out.external_uid").as("external_uid"),
      col("unflattened_struct_out.is_remarketing").as("is_remarketing"),
      col("unflattened_struct_out.mobile_app_instance_id")
        .as("mobile_app_instance_id"),
      col("unflattened_struct_out.traffic_source_code")
        .as("traffic_source_code"),
      col("unflattened_struct_out.external_request_id")
        .as("external_request_id"),
      col("unflattened_struct_out.stitch_group_id").as("stitch_group_id"),
      col("unflattened_struct_out.deal_type").as("deal_type"),
      col("unflattened_struct_out.ym_floor_id").as("ym_floor_id"),
      col("unflattened_struct_out.ym_bias_id").as("ym_bias_id"),
      col("unflattened_struct_out.bid_priority").as("bid_priority"),
      col("unflattened_struct_out.pricing_type").as("pricing_type"),
      col("unflattened_struct_out.buyer_charges").as("buyer_charges"),
      col("unflattened_struct_out.seller_charges").as("seller_charges"),
      col("unflattened_struct_out.revenue_value").as("revenue_value"),
      col("unflattened_struct_out.media_buy_rev_share_pct")
        .as("media_buy_rev_share_pct"),
      col("unflattened_struct_out.view_detection_enabled")
        .as("view_detection_enabled"),
      col("unflattened_struct_out.data_costs").as("data_costs"),
      col("unflattened_struct_out.device_make_id").as("device_make_id"),
      col("unflattened_struct_out.operating_system_family_id")
        .as("operating_system_family_id"),
      col("unflattened_struct_out.pricing_media_type").as("pricing_media_type"),
      col("unflattened_struct_out.buyer_trx_event_id").as("buyer_trx_event_id"),
      col("unflattened_struct_out.seller_trx_event_id")
        .as("seller_trx_event_id"),
      col("unflattened_struct_out.is_unit_of_trx").as("is_unit_of_trx"),
      col("unflattened_struct_out.revenue_auction_event_type")
        .as("revenue_auction_event_type"),
      col("unflattened_struct_out.is_prebid").as("is_prebid"),
      col("unflattened_struct_out.auction_timestamp").as("auction_timestamp"),
      col("unflattened_struct_out.clear_fees").as("clear_fees"),
      col("unflattened_struct_out.is_appnexus_cleared")
        .as("is_appnexus_cleared"),
      col("unflattened_struct_out.two_phase_reduction_applied")
        .as("two_phase_reduction_applied"),
      col("unflattened_struct_out.region_id").as("region_id"),
      col("unflattened_struct_out.media_company_id").as("media_company_id"),
      col("unflattened_struct_out.trade_agreement_id").as("trade_agreement_id"),
      col("unflattened_struct_out.cadence_modifier").as("cadence_modifier"),
      col("unflattened_struct_out.content_category_id")
        .as("content_category_id"),
      col("unflattened_struct_out.fx_rate_snapshot_id")
        .as("fx_rate_snapshot_id"),
      col("unflattened_struct_out.crossdevice_group_anon")
        .as("crossdevice_group_anon"),
      col("unflattened_struct_out.revenue_event_type_id")
        .as("revenue_event_type_id"),
      col("unflattened_struct_out.inv_code").as("inv_code"),
      col("unflattened_struct_out.bidder_id").as("bidder_id"),
      col("unflattened_struct_out.serving_fees_revshare")
        .as("serving_fees_revshare"),
      col("unflattened_struct_out.commission_revshare")
        .as("commission_revshare"),
      col("unflattened_struct_out.booked_revenue_adv_curr")
        .as("booked_revenue_adv_curr"),
      col("unflattened_struct_out.predict_type_cost").as("predict_type_cost"),
      col("unflattened_struct_out.ip_address").as("ip_address"),
      col("unflattened_struct_out.predict_goal").as("predict_goal"),
      col("unflattened_struct_out.seller_deduction").as("seller_deduction"),
      col("unflattened_struct_out.auction_service_fees")
        .as("auction_service_fees"),
      col("unflattened_struct_out.auction_service_deduction")
        .as("auction_service_deduction"),
      col("unflattened_struct_out.is_creative_hosted").as("is_creative_hosted"),
      col("unflattened_struct_out.creative_audit_status")
        .as("creative_audit_status"),
      col("unflattened_struct_out.datacenter_id").as("datacenter_id"),
      col("unflattened_struct_out.truncate_ip").as("truncate_ip"),
      col("unflattened_struct_out.is_exclusive").as("is_exclusive"),
      col("unflattened_struct_out.vp_expose_gender").as("vp_expose_gender"),
      col("unflattened_struct_out.vp_expose_age").as("vp_expose_age"),
      col("unflattened_struct_out.crossdevice_graph_cost")
        .as("crossdevice_graph_cost"),
      col("unflattened_struct_out.player_width").as("player_width"),
      col("unflattened_struct_out.player_height").as("player_height"),
      col("unflattened_struct_out.external_creative_id")
        .as("external_creative_id"),
      col("unflattened_struct_out.age_bucket").as("age_bucket"),
      col("unflattened_struct_out.bidder_seat_id").as("bidder_seat_id"),
      col("unflattened_struct_out.billing_period_id").as("billing_period_id"),
      col("unflattened_struct_out.flight_id").as("flight_id"),
      col("unflattened_struct_out.split_id").as("split_id"),
      col("unflattened_struct_out.total_partner_fees_microcents")
        .as("total_partner_fees_microcents"),
      col("unflattened_struct_out.net_media_cost_dollars_cpm")
        .as("net_media_cost_dollars_cpm"),
      col("unflattened_struct_out.total_data_costs_microcents")
        .as("total_data_costs_microcents"),
      col("unflattened_struct_out.total_profit_microcents")
        .as("total_profit_microcents"),
      col("unflattened_struct_out.curator_member_id").as("curator_member_id"),
      col("unflattened_struct_out.eap").as("eap"),
      col("unflattened_struct_out.ecp").as("ecp"),
      col("unflattened_struct_out.buyer_bid").as("buyer_bid"),
      col("unflattened_struct_out.reserve_price").as("reserve_price"),
      col("unflattened_struct_out.serving_fees_cpm").as("serving_fees_cpm"),
      col("unflattened_struct_out.can_convert").as("can_convert"),
      col("unflattened_struct_out.control_creative_id")
        .as("control_creative_id"),
      col("unflattened_struct_out.commission_cpm").as("commission_cpm"),
      col("unflattened_struct_out.creative_overage_fees")
        .as("creative_overage_fees"),
      col("unflattened_struct_out.imps_for_budget_caps_pacing")
        .as("imps_for_budget_caps_pacing"),
      col("unflattened_struct_out.buyer_spend").as("buyer_spend"),
      col("unflattened_struct_out.actual_bid").as("actual_bid"),
      col("unflattened_struct_out.campaign_group_type_id")
        .as("campaign_group_type_id"),
      col("unflattened_struct_out.predicted_kpi_event_rate")
        .as("predicted_kpi_event_rate"),
      col("unflattened_struct_out.total_segment_data_costs_microcents")
        .as("total_segment_data_costs_microcents"),
      col("unflattened_struct_out.total_feature_costs_microcents")
        .as("total_feature_costs_microcents"),
      col("unflattened_struct_out.counterparty_ruleset_type")
        .as("counterparty_ruleset_type"),
      col("unflattened_struct_out.log_product_ads").as("log_product_ads"),
      col("unflattened_struct_out.hb_source").as("hb_source"),
      col("unflattened_struct_out.buyer_line_item_currency")
        .as("buyer_line_item_currency"),
      col("unflattened_struct_out.deal_line_item_currency")
        .as("deal_line_item_currency"),
      col("unflattened_struct_out.is_curated").as("is_curated"),
      col("unflattened_struct_out.personal_identifiers_experimental")
        .as("personal_identifiers_experimental"),
      col("unflattened_struct_out.postal_code_ext_id").as("postal_code_ext_id"),
      col("unflattened_struct_out.ecpm_conversion_rate")
        .as("ecpm_conversion_rate"),
      col("unflattened_struct_out.targeted_segment_details_by_id_type")
        .as("targeted_segment_details_by_id_type"),
      col("unflattened_struct_out.targeted_segment_details")
        .as("targeted_segment_details"),
      col("unflattened_struct_out.personal_identifiers")
        .as("personal_identifiers"),
      col("unflattened_struct_out.district_postal_code_lists")
        .as("district_postal_code_lists"),
      col("unflattened_struct_out.video_served_timestamp")
        .as("video_served_timestamp"),
      col("unflattened_struct_out.video_started_timestamp")
        .as("video_started_timestamp"),
      col("unflattened_struct_out.video_skipped_timestamp")
        .as("video_skipped_timestamp"),
      col("unflattened_struct_out.video_errored_timestamp")
        .as("video_errored_timestamp"),
      col("unflattened_struct_out.video_hit_25_pct_timestamp")
        .as("video_hit_25_pct_timestamp"),
      col("unflattened_struct_out.video_hit_50_pct_timestamp")
        .as("video_hit_50_pct_timestamp"),
      col("unflattened_struct_out.video_hit_75_pct_timestamp")
        .as("video_hit_75_pct_timestamp"),
      col("unflattened_struct_out.video_completed_timestamp")
        .as("video_completed_timestamp"),
      col("unflattened_struct_out.fallback_ad_index").as("fallback_ad_index"),
      col("unflattened_struct_out.is_transacted").as("is_transacted"),
      col("unflattened_struct_out.is_winning_events").as("is_winning_events"),
      col("unflattened_struct_out.is_service_events").as("is_service_events"),
      col("unflattened_struct_out.buyer_dpvp_bitmap").as("buyer_dpvp_bitmap"),
      col("unflattened_struct_out.seller_dpvp_bitmap").as("seller_dpvp_bitmap"),
      col("unflattened_struct_out.imp_media_cost_dollars_cpm")
        .as("imp_media_cost_dollars_cpm"),
      col("unflattened_struct_out.imp_booked_revenue_dollars")
        .as("imp_booked_revenue_dollars"),
      col("unflattened_struct_out.imp_seller_revenue_cpm").as(
        "imp_seller_revenue_cpm"
      )
    )

}
