name: demo_scala_project
description: ''
version: '1.2'
author: abhinav+demo@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: demo_scala_project
  parentArtefactID: demo_team_abhinav
  buildSystem: maven
  author: null
  createdAt: '2023-09-25 16:30:33'
pipelines:
  pipelines/customer_orders:
    name: customer_orders
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-09-25 16:30:33'
    datasets:
      inputs:
      - datasets/customers
      - datasets/new_customers
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-09-25 16:30:48'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2023-09-25 16:32:17'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2023-09-25 16:32:17'
  datasets/customers:
    name: customers
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2023-09-25 16:32:51'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2023-09-25 16:32:51'
  datasets/csv:
    name: csv
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-01-29 14:16:14'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-01-29 14:16:14'
  datasets/new_customers:
    name: new_customers
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-02-03 09:42:54'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-02-03 09:42:54'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.0.4
  gems:
    gems/csv:
      name: csv
      category: Source/Target
      subCategory: File
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - src/main/scala/demo_team_abhinav/demo_scala_project/gems/csv.scala
      gemType: DatasetGem
      dependencies: []
      createdAt: '2025-02-03 09:27:51'
    gems/Filter:
      name: Filter
      category: Transform
      subCategory: ''
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - src/main/scala/demo_team_abhinav/demo_scala_project/gems/Filter.scala
      gemType: ComponentGem
      dependencies: []
      createdAt: '2025-02-03 09:29:00'
    gems/Limit:
      name: Limit
      category: Transform
      subCategory: ''
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - src/main/scala/demo_team_abhinav/demo_scala_project/gems/Limit.scala
      gemType: ComponentGem
      dependencies: []
      createdAt: '2025-02-03 09:40:29'
  dependencies: null
functions:
  author: null
  createdAt: '2023-09-25 16:30:33'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-13T12:57:38.512199Z'
  name: plibMaven
  version: 8.7.1
  id: '817591910'
  createdAt: '2024-08-13T12:57:38.512153Z'
  enabled: true
  entity: Project
projectDependencies:
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.6
    isDefault: true
    author: null
    createdAt: '2024-11-18 15:09:14'
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-11-18 15:09:18'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
