package graph

import io.prophecy.libs._
import udfs.PipelineInitCode._
import udfs.UDFs._
import udfs.ColumnFunctions._
import config.Context
import org.apache.spark._
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.expressions._
import java.time._

object Reformat_log_dw_bid {

  def apply(context: Context, in: DataFrame): DataFrame =
    in.select(
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("date_time")
        .cast(LongType)
        .as("date_time"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("auction_id_64")
        .cast(LongType)
        .as("auction_id_64"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("price")
        .cast(DoubleType)
        .as("price"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("member_id")
        .cast(IntegerType)
        .as("member_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("advertiser_id")
        .cast(IntegerType)
        .as("advertiser_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("campaign_group_id")
        .cast(IntegerType)
        .as("campaign_group_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("campaign_id")
        .cast(IntegerType)
        .as("campaign_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("creative_id")
        .cast(IntegerType)
        .as("creative_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("creative_freq")
        .cast(IntegerType)
        .as("creative_freq"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("creative_rec")
        .cast(IntegerType)
        .as("creative_rec"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("advertiser_freq")
        .cast(IntegerType)
        .as("advertiser_freq"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("advertiser_rec")
        .cast(IntegerType)
        .as("advertiser_rec"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("is_remarketing")
        .cast(IntegerType)
        .as("is_remarketing"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("user_group_id")
        .cast(IntegerType)
        .as("user_group_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("media_buy_cost")
        .cast(DoubleType)
        .as("media_buy_cost"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("is_default")
        .cast(IntegerType)
        .as("is_default"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("pub_rule_id")
        .cast(IntegerType)
        .as("pub_rule_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("media_buy_rev_share_pct")
        .cast(DoubleType)
        .as("media_buy_rev_share_pct"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("pricing_type")
        .as("pricing_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("can_convert")
        .cast(IntegerType)
        .as("can_convert"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("is_control")
        .cast(IntegerType)
        .as("is_control"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("control_pct")
        .cast(DoubleType)
        .as("control_pct"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("control_creative_id")
        .cast(IntegerType)
        .as("control_creative_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("cadence_modifier")
        .cast(DoubleType)
        .as("cadence_modifier"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("advertiser_currency")
        .as("advertiser_currency"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("advertiser_exchange_rate")
        .cast(DoubleType)
        .as("advertiser_exchange_rate"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("insertion_order_id")
        .cast(IntegerType)
        .as("insertion_order_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("predict_type")
        .cast(IntegerType)
        .as("predict_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("predict_type_goal")
        .cast(IntegerType)
        .as("predict_type_goal"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("revenue_value_dollars")
        .cast(DoubleType)
        .as("revenue_value_dollars"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("revenue_value_adv_curr")
        .cast(DoubleType)
        .as("revenue_value_adv_curr"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("commission_cpm")
        .cast(DoubleType)
        .as("commission_cpm"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("commission_revshare")
        .cast(DoubleType)
        .as("commission_revshare"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("serving_fees_cpm")
        .cast(DoubleType)
        .as("serving_fees_cpm"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("serving_fees_revshare")
        .cast(DoubleType)
        .as("serving_fees_revshare"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("publisher_currency")
        .as("publisher_currency"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("publisher_exchange_rate")
        .cast(DoubleType)
        .as("publisher_exchange_rate"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("payment_type")
        .cast(IntegerType)
        .as("payment_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("payment_value")
        .cast(DoubleType)
        .as("payment_value"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("creative_group_freq")
        .cast(IntegerType)
        .as("creative_group_freq"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("creative_group_rec")
        .cast(IntegerType)
        .as("creative_group_rec"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("revenue_type")
        .cast(IntegerType)
        .as("revenue_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("apply_cost_on_default")
        .cast(IntegerType)
        .as("apply_cost_on_default"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("instance_id")
        .cast(IntegerType)
        .as("instance_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("vp_expose_age")
        .cast(IntegerType)
        .as("vp_expose_age"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("vp_expose_gender")
        .cast(IntegerType)
        .as("vp_expose_gender"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("targeted_segments")
        .as("targeted_segments"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("ttl")
        .cast(IntegerType)
        .as("ttl"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("auction_timestamp")
        .cast(LongType)
        .as("auction_timestamp"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("data_costs")
        .as("data_costs"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("targeted_segment_list")
        .as("targeted_segment_list"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("campaign_group_freq")
        .cast(IntegerType)
        .as("campaign_group_freq"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("campaign_group_rec")
        .cast(IntegerType)
        .as("campaign_group_rec"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("insertion_order_freq")
        .cast(IntegerType)
        .as("insertion_order_freq"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("insertion_order_rec")
        .cast(IntegerType)
        .as("insertion_order_rec"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("buyer_gender")
        .as("buyer_gender"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("buyer_age")
        .cast(IntegerType)
        .as("buyer_age"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("custom_model_id")
        .cast(IntegerType)
        .as("custom_model_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("custom_model_last_modified")
        .cast(LongType)
        .as("custom_model_last_modified"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("custom_model_output_code")
        .as("custom_model_output_code"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("bid_priority")
        .cast(IntegerType)
        .as("bid_priority"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("explore_disposition")
        .cast(IntegerType)
        .as("explore_disposition"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("revenue_auction_event_type")
        .cast(IntegerType)
        .as("revenue_auction_event_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("campaign_group_models")
        .as("campaign_group_models"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("impression_transaction_type")
        .cast(IntegerType)
        .as("impression_transaction_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("is_deferred")
        .cast(IntegerType)
        .as("is_deferred"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("log_type")
        .cast(IntegerType)
        .as("log_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("crossdevice_group_anon")
        .as("crossdevice_group_anon"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("fx_rate_snapshot_id")
        .cast(IntegerType)
        .as("fx_rate_snapshot_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("crossdevice_graph_cost")
        .as("crossdevice_graph_cost"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("revenue_event_type_id")
        .cast(IntegerType)
        .as("revenue_event_type_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("targeted_segment_details")
        .as("targeted_segment_details"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("insertion_order_budget_interval_id")
        .cast(IntegerType)
        .as("insertion_order_budget_interval_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("campaign_group_budget_interval_id")
        .cast(IntegerType)
        .as("campaign_group_budget_interval_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("cold_start_price_type")
        .cast(IntegerType)
        .as("cold_start_price_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("discovery_state")
        .cast(IntegerType)
        .as("discovery_state"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("revenue_info")
        .as("revenue_info"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("use_revenue_info")
        .cast(BooleanType)
        .as("use_revenue_info"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("sales_tax_rate_pct")
        .cast(DoubleType)
        .as("sales_tax_rate_pct"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("targeted_crossdevice_graph_id")
        .cast(IntegerType)
        .as("targeted_crossdevice_graph_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("product_feed_id")
        .cast(IntegerType)
        .as("product_feed_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("item_selection_strategy_id")
        .cast(IntegerType)
        .as("item_selection_strategy_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("discovery_prediction")
        .cast(DoubleType)
        .as("discovery_prediction"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("bidding_host_id")
        .cast(IntegerType)
        .as("bidding_host_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("split_id")
        .cast(IntegerType)
        .as("split_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("excluded_targeted_segment_details")
        .as("excluded_targeted_segment_details"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("predicted_kpi_event_rate")
        .cast(DoubleType)
        .as("predicted_kpi_event_rate"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("has_crossdevice_reach_extension")
        .cast(BooleanType)
        .as("has_crossdevice_reach_extension"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("advertiser_expected_value_ecpm_ac")
        .cast(DoubleType)
        .as("advertiser_expected_value_ecpm_ac"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("bpp_multiplier")
        .cast(DoubleType)
        .as("bpp_multiplier"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("bpp_offset")
        .cast(DoubleType)
        .as("bpp_offset"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("bid_modifier")
        .cast(DoubleType)
        .as("bid_modifier"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("payment_value_microcents")
        .cast(LongType)
        .as("payment_value_microcents"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("crossdevice_graph_membership")
        .as("crossdevice_graph_membership"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("valuation_landscape")
        .as("valuation_landscape"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("line_item_currency")
        .as("line_item_currency"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("measurement_fee_cpm_usd")
        .cast(DoubleType)
        .as("measurement_fee_cpm_usd"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("measurement_provider_id")
        .cast(IntegerType)
        .as("measurement_provider_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("measurement_provider_member_id")
        .cast(IntegerType)
        .as("measurement_provider_member_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("offline_attribution_provider_member_id")
        .cast(IntegerType)
        .as("offline_attribution_provider_member_id"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("offline_attribution_cost_usd_cpm")
        .cast(DoubleType)
        .as("offline_attribution_cost_usd_cpm"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("targeted_segment_details_by_id_type")
        .as("targeted_segment_details_by_id_type"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("offline_attribution")
        .as("offline_attribution"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("frequency_cap_type_internal")
        .cast(IntegerType)
        .as("frequency_cap_type_internal"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("modeled_cap_did_override_line_item_daily_cap")
        .cast(BooleanType)
        .as("modeled_cap_did_override_line_item_daily_cap"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("modeled_cap_user_sample_rate")
        .cast(DoubleType)
        .as("modeled_cap_user_sample_rate"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("bid_rate")
        .cast(DoubleType)
        .as("bid_rate"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("district_postal_code_lists")
        .as("district_postal_code_lists"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("pre_bpp_price")
        .cast(DoubleType)
        .as("pre_bpp_price"),
      col("in_f_convert_log_dw_imptracker_to_log_dw_bid")
        .getField("feature_tests_bitmap")
        .cast(IntegerType)
        .as("feature_tests_bitmap")
    )

}
