package graph

import io.prophecy.libs._
import udfs.PipelineInitCode._
import udfs.UDFs._
import udfs.ColumnFunctions._
import config.Context
import org.apache.spark._
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.expressions._
import java.time._

object Reformat_log_impbus_impressions {

  def apply(context: Context, in: DataFrame): DataFrame =
    in.select(
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("date_time")
        .cast(LongType)
        .as("date_time"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("auction_id_64")
        .cast(LongType)
        .as("auction_id_64"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("user_id_64")
        .cast(LongType)
        .as("user_id_64"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("tag_id")
        .cast(IntegerType)
        .as("tag_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ip_address")
        .as("ip_address"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("venue_id")
        .cast(IntegerType)
        .as("venue_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("site_domain")
        .as("site_domain"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("width")
        .cast(IntegerType)
        .as("width"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("height")
        .cast(IntegerType)
        .as("height"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("geo_country")
        .as("geo_country"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("geo_region")
        .as("geo_region"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("gender")
        .as("gender"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("age")
        .cast(IntegerType)
        .as("age"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("bidder_id")
        .cast(IntegerType)
        .as("bidder_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_member_id")
        .cast(IntegerType)
        .as("seller_member_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("buyer_member_id")
        .cast(IntegerType)
        .as("buyer_member_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("creative_id")
        .cast(IntegerType)
        .as("creative_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("imp_blacklist_or_fraud")
        .cast(IntegerType)
        .as("imp_blacklist_or_fraud"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("imp_bid_on")
        .cast(IntegerType)
        .as("imp_bid_on"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("buyer_bid")
        .cast(DoubleType)
        .as("buyer_bid"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("buyer_spend")
        .cast(DoubleType)
        .as("buyer_spend"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_revenue")
        .cast(DoubleType)
        .as("seller_revenue"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("num_of_bids")
        .cast(IntegerType)
        .as("num_of_bids"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ecp")
        .cast(DoubleType)
        .as("ecp"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("reserve_price")
        .cast(DoubleType)
        .as("reserve_price"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("inv_code")
        .as("inv_code"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("call_type")
        .as("call_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("inventory_source_id")
        .cast(IntegerType)
        .as("inventory_source_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("cookie_age")
        .cast(IntegerType)
        .as("cookie_age"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("brand_id")
        .cast(IntegerType)
        .as("brand_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("cleared_direct")
        .cast(IntegerType)
        .as("cleared_direct"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("forex_allowance")
        .cast(DoubleType)
        .as("forex_allowance"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("fold_position")
        .cast(IntegerType)
        .as("fold_position"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("external_inv_id")
        .cast(IntegerType)
        .as("external_inv_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("imp_type")
        .cast(IntegerType)
        .as("imp_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_delivered")
        .cast(IntegerType)
        .as("is_delivered"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_dw")
        .cast(IntegerType)
        .as("is_dw"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("publisher_id")
        .cast(IntegerType)
        .as("publisher_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("site_id")
        .cast(IntegerType)
        .as("site_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("content_category_id")
        .cast(IntegerType)
        .as("content_category_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("datacenter_id")
        .cast(IntegerType)
        .as("datacenter_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("eap")
        .cast(DoubleType)
        .as("eap"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("user_tz_offset")
        .cast(IntegerType)
        .as("user_tz_offset"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("user_group_id")
        .cast(IntegerType)
        .as("user_group_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("pub_rule_id")
        .cast(IntegerType)
        .as("pub_rule_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("media_type")
        .cast(IntegerType)
        .as("media_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("operating_system")
        .cast(IntegerType)
        .as("operating_system"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("browser")
        .cast(IntegerType)
        .as("browser"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("language")
        .cast(IntegerType)
        .as("language"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("application_id")
        .as("application_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("user_locale")
        .as("user_locale"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("inventory_url_id")
        .cast(IntegerType)
        .as("inventory_url_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("audit_type")
        .cast(IntegerType)
        .as("audit_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("shadow_price")
        .cast(DoubleType)
        .as("shadow_price"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("impbus_id")
        .cast(IntegerType)
        .as("impbus_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("buyer_currency")
        .as("buyer_currency"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("buyer_exchange_rate")
        .cast(DoubleType)
        .as("buyer_exchange_rate"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_currency")
        .as("seller_currency"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_exchange_rate")
        .cast(DoubleType)
        .as("seller_exchange_rate"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("vp_expose_domains")
        .cast(IntegerType)
        .as("vp_expose_domains"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("vp_expose_categories")
        .cast(IntegerType)
        .as("vp_expose_categories"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("vp_expose_pubs")
        .cast(IntegerType)
        .as("vp_expose_pubs"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("vp_expose_tag")
        .cast(IntegerType)
        .as("vp_expose_tag"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_exclusive")
        .cast(IntegerType)
        .as("is_exclusive"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("bidder_instance_id")
        .cast(IntegerType)
        .as("bidder_instance_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("visibility_profile_id")
        .cast(IntegerType)
        .as("visibility_profile_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("truncate_ip")
        .cast(IntegerType)
        .as("truncate_ip"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("device_id")
        .cast(IntegerType)
        .as("device_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("carrier_id")
        .cast(IntegerType)
        .as("carrier_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("creative_audit_status")
        .cast(IntegerType)
        .as("creative_audit_status"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_creative_hosted")
        .cast(IntegerType)
        .as("is_creative_hosted"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("city")
        .cast(IntegerType)
        .as("city"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("latitude")
        .as("latitude"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("longitude")
        .as("longitude"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("device_unique_id")
        .as("device_unique_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("supply_type")
        .cast(IntegerType)
        .as("supply_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_toolbar")
        .cast(IntegerType)
        .as("is_toolbar"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("deal_id")
        .cast(IntegerType)
        .as("deal_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("vp_bitmap")
        .cast(LongType)
        .as("vp_bitmap"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ttl")
        .cast(IntegerType)
        .as("ttl"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("view_detection_enabled")
        .cast(IntegerType)
        .as("view_detection_enabled"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ozone_id")
        .cast(IntegerType)
        .as("ozone_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_performance")
        .cast(IntegerType)
        .as("is_performance"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("sdk_version")
        .as("sdk_version"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("inventory_session_frequency")
        .cast(IntegerType)
        .as("inventory_session_frequency"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("bid_price_type")
        .cast(IntegerType)
        .as("bid_price_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("device_type")
        .cast(IntegerType)
        .as("device_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("dma")
        .cast(IntegerType)
        .as("dma"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("postal")
        .as("postal"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("package_id")
        .cast(IntegerType)
        .as("package_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("spend_protection")
        .cast(IntegerType)
        .as("spend_protection"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_secure")
        .cast(IntegerType)
        .as("is_secure"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("estimated_view_rate")
        .cast(DoubleType)
        .as("estimated_view_rate"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("external_request_id")
        .as("external_request_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("viewdef_definition_id_buyer_member")
        .cast(IntegerType)
        .as("viewdef_definition_id_buyer_member"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("spend_protection_pixel_id")
        .cast(IntegerType)
        .as("spend_protection_pixel_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("external_uid")
        .as("external_uid"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("request_uuid")
        .as("request_uuid"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("mobile_app_instance_id")
        .cast(IntegerType)
        .as("mobile_app_instance_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("traffic_source_code")
        .as("traffic_source_code"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("stitch_group_id")
        .as("stitch_group_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("deal_type")
        .cast(IntegerType)
        .as("deal_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ym_floor_id")
        .cast(IntegerType)
        .as("ym_floor_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ym_bias_id")
        .cast(IntegerType)
        .as("ym_bias_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("estimated_view_rate_over_total")
        .cast(DoubleType)
        .as("estimated_view_rate_over_total"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("device_make_id")
        .cast(IntegerType)
        .as("device_make_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("operating_system_family_id")
        .cast(IntegerType)
        .as("operating_system_family_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("tag_sizes")
        .as("tag_sizes"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_transaction_def")
        .as("seller_transaction_def"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("buyer_transaction_def")
        .as("buyer_transaction_def"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("predicted_video_view_info")
        .as("predicted_video_view_info"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("auction_url")
        .as("auction_url"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("allowed_media_types")
        .as("allowed_media_types"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_imp_rejecter_applied")
        .cast(BooleanType)
        .as("is_imp_rejecter_applied"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("imp_rejecter_do_auction")
        .cast(BooleanType)
        .as("imp_rejecter_do_auction"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("geo_location")
        .as("geo_location"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_bid_currency_conversion_rate")
        .cast(DoubleType)
        .as("seller_bid_currency_conversion_rate"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seller_bid_currency_code")
        .as("seller_bid_currency_code"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_prebid")
        .cast(BooleanType)
        .as("is_prebid"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("default_referrer_url")
        .as("default_referrer_url"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("engagement_rates")
        .as("engagement_rates"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("fx_rate_snapshot_id")
        .cast(IntegerType)
        .as("fx_rate_snapshot_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("payment_type")
        .cast(IntegerType)
        .as("payment_type"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("apply_cost_on_default")
        .cast(IntegerType)
        .as("apply_cost_on_default"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("media_buy_cost")
        .cast(DoubleType)
        .as("media_buy_cost"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("media_buy_rev_share_pct")
        .cast(DoubleType)
        .as("media_buy_rev_share_pct"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("auction_duration_ms")
        .cast(IntegerType)
        .as("auction_duration_ms"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("expected_events")
        .cast(IntegerType)
        .as("expected_events"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("anonymized_user_info")
        .as("anonymized_user_info"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("region_id")
        .cast(IntegerType)
        .as("region_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("media_company_id")
        .cast(IntegerType)
        .as("media_company_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("gdpr_consent_cookie")
        .as("gdpr_consent_cookie"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("subject_to_gdpr")
        .cast(BooleanType)
        .as("subject_to_gdpr"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("browser_code_id")
        .cast(IntegerType)
        .as("browser_code_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_prebid_server_included")
        .cast(IntegerType)
        .as("is_prebid_server_included"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("seat_id")
        .cast(IntegerType)
        .as("seat_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("uid_source")
        .cast(IntegerType)
        .as("uid_source"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_whiteops_scanned")
        .cast(BooleanType)
        .as("is_whiteops_scanned"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("pred_info")
        .cast(IntegerType)
        .as("pred_info"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("crossdevice_groups")
        .as("crossdevice_groups"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_amp")
        .cast(BooleanType)
        .as("is_amp"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("hb_source")
        .cast(IntegerType)
        .as("hb_source"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("external_campaign_id")
        .as("external_campaign_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("log_product_ads")
        .as("log_product_ads"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("ss_native_assembly_enabled")
        .cast(BooleanType)
        .as("ss_native_assembly_enabled"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("emp")
        .cast(DoubleType)
        .as("emp"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("personal_identifiers")
        .as("personal_identifiers"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("personal_identifiers_experimental")
        .as("personal_identifiers_experimental"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("postal_code_ext_id")
        .cast(IntegerType)
        .as("postal_code_ext_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("hashed_ip")
        .as("hashed_ip"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("external_deal_code")
        .as("external_deal_code"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("creative_duration")
        .cast(IntegerType)
        .as("creative_duration"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("openrtb_req_subdomain")
        .as("openrtb_req_subdomain"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("creative_media_subtype_id")
        .cast(IntegerType)
        .as("creative_media_subtype_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("is_private_auction")
        .cast(BooleanType)
        .as("is_private_auction"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("private_auction_eligible")
        .cast(BooleanType)
        .as("private_auction_eligible"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("client_request_id")
        .as("client_request_id"),
      col("in_f_convert_log_impbus_imptracker_to_log_impbus_impressions")
        .getField("chrome_traffic_label")
        .cast(IntegerType)
        .as("chrome_traffic_label")
    )

}
